#!/bin/sh
# POSIX-compatible installer (no 'pipefail' so dash/busybox /bin/sh works)
set -eu

RAW_BASE="${RAW_BASE:-https://raw.githubusercontent.com/kha333n/command-line-aliases/master}"

BASH_TARGET="$HOME/.config/aliases/bash_aliases.sh"
FISH_TARGET="$HOME/.config/fish/conf.d/aliases.fish"

have() { command -v "$1" >/dev/null 2>&1; }

fetch() {
  # fetch <url> <dest>
  url="$1"; dest="$2"
  if have curl; then
    curl -fsSL "$url" -o "$dest"
  elif have wget; then
    wget -qO "$dest" "$url"
  else
    echo "ERROR: need curl or wget" >&2
    exit 1
  fi
}

# mkdir -p (portable)
mkdir_p() {
  [ -d "$1" ] || mkdir -p "$1"
}

mkdir_p "$HOME/.config/aliases"
mkdir_p "$HOME/.config/fish/conf.d"

echo "[*] Installing Bash aliases (if Bash present)…"
if have bash || [ "${BASH_VERSION-}" ]; then
  fetch "$RAW_BASE/aliases/bash_aliases.sh" "$BASH_TARGET"
  # Ensure source block exists in ~/.bashrc (idempotent)
  if [ -f "$HOME/.bashrc" ]; then
    if ! grep -q "### ALIASES:BEGIN ###" "$HOME/.bashrc"; then
      {
        printf "\n### ALIASES:BEGIN ###\n"
        printf "[ -f \"%s\" ] && . \"%s\"\n" "$BASH_TARGET" "$BASH_TARGET"
        printf "### ALIASES:END ###\n"
      } >> "$HOME/.bashrc"
      echo "    Appended source block to ~/.bashrc"
    else
      echo "    Source block already present in ~/.bashrc"
    fi
  else
    # Minimal ~/.bashrc
    {
      echo "# ~/.bashrc generated by alias installer"
      printf "[ -f \"%s\" ] && . \"%s\"\n" "$BASH_TARGET" "$BASH_TARGET"
    } > "$HOME/.bashrc"
    echo "    Created ~/.bashrc with source block"
  fi
else
  echo "    Bash not detected; skipping."
fi

echo "[*] Installing Fish aliases (if Fish present)…"
if have fish; then
  fetch "$RAW_BASE/aliases/fish_aliases.fish" "$FISH_TARGET"
  echo "    Placed at $FISH_TARGET (auto-sourced by Fish)"
else
  echo "    Fish not detected; skipping."
fi

echo ""
echo "✅ Done. For immediate use:"
echo "   - Bash:   source ~/.bashrc"
echo "   - Fish:   exec fish (or open a new Fish session)"
