#!/usr/bin/env bash
set -euo pipefail

RAW_BASE="${RAW_BASE:-https://RAW_BASE}"
BASH_TARGET="${HOME}/.config/aliases/bash_aliases.sh"
FISH_TARGET="${HOME}/.config/fish/conf.d/aliases.fish"

have() { command -v "$1" >/dev/null 2>&1; }
fetch() {
  local url="$1" dest="$2"
  if command -v curl >/dev/null 2>&1; then
    curl -fsSL "$url" -o "$dest"
  elif command -v wget >/dev/null 2>&1; then
    wget -qO "$dest" "$url"
  else
    echo "ERROR: curl or wget required." >&2
    exit 1
  fi
}

mkdir -p "${HOME}/.config/aliases"
mkdir -p "${HOME}/.config/fish/conf.d"

echo "[*] Installing Bash aliases…"
if have bash || [ -n "${BASH_VERSION:-}" ]; then
  fetch "${RAW_BASE}/aliases/bash_aliases.sh" "$BASH_TARGET"
  chmod +x "$BASH_TARGET" || true

  if [ -f "${HOME}/.bashrc" ]; then
    if ! grep -q "### ALIASES:BEGIN ###" "${HOME}/.bashrc"; then
      {
        echo ""
        echo "### ALIASES:BEGIN ###"
        echo "[ -f \"$BASH_TARGET\" ] && . \"$BASH_TARGET\""
        echo "### ALIASES:END ###"
      } >> "${HOME}/.bashrc"
      echo "    Appended source block to ~/.bashrc"
    else
      echo "    Source block already present in ~/.bashrc"
    fi
  else
    cat > "${HOME}/.bashrc" <<'EOF'
# ~/.bashrc generated by alias installer
[ -f "$HOME/.config/aliases/bash_aliases.sh" ] && . "$HOME/.config/aliases/bash_aliases.sh"
EOF
    echo "    Created minimal ~/.bashrc"
  fi
else
  echo "    Bash not detected; skipping."
fi

echo "[*] Installing Fish aliases…"
if have fish; then
  fetch "${RAW_BASE}/aliases/fish_aliases.fish" "$FISH_TARGET"
  echo "    Placed at $FISH_TARGET (auto-sourced by Fish)"
else
  echo "    Fish not detected; skipping."
fi

echo ""
echo "✅ Done. Open a new shell (or 'source ~/.bashrc' / 'exec fish')."
